apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432 #default port for postgres image
      #environment variables to set up the postgres database and also to connect to the database from the voting and result application
      env: 
        - name: POSTGRES_DB
          value: "votingapp"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        
