apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379 #port on which the service will be exposed
      targetPort: 6379 #port on which the redis pod is listening
  selector:
    name: redis-pod #this is the label of the redis pod that we want to target with this service
    app: demo-voting-app #this stays same as we need this to be in the same cluster as all the other pods of the application