apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort #this is the type of service that we want to create. NodePort service exposes the service on a static port on each node in the cluster. This allows us to access the service from outside the cluster using the node's IP address and the NodePort.
  ports:
    - port: 80 #port on which the service will be exposed
      targetPort: 80 #port on which the result pod is listening
      nodePort: 30005 #this is the port on which the service will be exposed on each node in the cluster, we can access the service using <NodeIP>:30005
  selector:
    name: result-app-pod #this is the label of the result-app pod that we want to target with this service
    app: demo-voting-app #this stays same as we need this to be in the same cluster as all the other pods of the application