apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort #this is the type of service that we want to create, it will expose the service on a port on each node in the cluster
  ports:
    - port: 80 #port on which the service will be exposed
      targetPort: 80 #port on which the voting pod is listening
      nodePort: 30004 #this is the port on which the service will be exposed on each node in the cluster, we can access the service using <NodeIP>:30004
  selector:
    name: voting-app-pod #this is the label of the voting-app pod that we want to target with this service
    app: demo-voting-app #this stays same as we need this to be in the same cluster as all the other pods of the application